apiVersion: v1
kind: Service
metadata:
    name: "dnkaki01-57ec"
    labels:
        app: "dnkaki01-57ec"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dnkaki01-57ec"