on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dnkaciregistry.azurecr.io
        username: ${{ secrets.acr_dnkaciregistry_username }}
        password: ${{ secrets.acr_dnkaciregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dnkaciregistry.azurecr.io/dnkaki01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dnkaciregistry.azurecr.io/dnkaki01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dnkaki01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dnk-aki01ba35 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dnk-aki01ba35`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dnk-aki01ba35
        container-registry-url: dnkaciregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_dnkaciregistry_username }}
        container-registry-password: ${{ secrets.acr_dnkaciregistry_password }}
        secret-name: dnkaki01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dnk-aki01ba35
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          dnkaciregistry.azurecr.io/dnkaki01:${{ github.sha }}
        imagepullsecrets: |
          dnkaki01dockerauth
